-- jellybeans.nvim (:colorscheme jellybeans / jellybeans-muted / jellybeans-warm / jellybeans-hc ...)
local pack = require("config.pack")
pack.lazy({ "wtfox/jellybeans.nvim" }, {}, function()
  require("jellybeans").setup({ transparent = true })
end)
