-- nightfox (:colorscheme nightfox / nordfox / duskfox / carbonfox / dawnfox / dayfox / terafox)
local pack = require("config.pack")
pack.lazy({ "EdenEast/nightfox.nvim" }, {}, function()
  require("nightfox").setup({ options = { transparent = true } })
end)
