-- rose-pine (:colorscheme rose-pine / rose-pine-main / -moon / -dawn)
local pack = require("config.pack")
pack.lazy({ { "rose-pine/neovim", name = "rose-pine" } }, {}, function()
  require("rose-pine").setup({ groups = { h6 = "foam" } })
end)
